
name: mlrun-project-workflow
on:
  push:
    branches:
      - master
    # paths:
    #   - 'code/*'
jobs:
  submit-project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install mlrun
      run: python -m pip install git+https://github.com/mlrun/mlrun.git@gitops
    - name: Submit project
      run: python -m mlrun project -n skgh -u ./project.yaml -r main -p v3io:///users/admin/kfp
      env:
        V3IO_USERNAME: admin
        V3IO_API: ${{ secrets.V3IO_API }}
        V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        MLRUN_DBPATH: ${{ secrets.MLRUN_DBPATH }}
